package colaboraciones;

public enum TipoColaboracion {
    DONACION_DE_DINERO,
    DONACION_DE_VIANDAS,
    DISTRIBUCION_DE_VIANDAS,
    HACERSE_CARGO,
    REGISTRO_DE_PERSONAS_VULNERABLES,
    OFRECER_PRODUCTO_RECONOCIMIENTO
}
